- platform: template
  sensors:
    living_room_motion_sensor_battery_low:
      entity_id: zwave.fibaro_system_fgms001zw5_motion_sensor_5
      value_template: >
        {% if states.zwave.fibaro_system_fgms001zw5_motion_sensor_5 %}
        {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor_5.attributes.battery_level < 10 }}
        {% else %}
        ??
        {% endif %}
    johnny_asleep:
      friendly_name: Johnny asleep
      entity_id: sensor.fibaro_system_fgwpef_wall_plug_gen5_power_3_4
      value_template: >
        {% if states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power_3_4 %}
          {% if states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power_3_4.state | float > 0.0 %}
            {{ true }}
          {% elif (as_timestamp(now()) - as_timestamp(states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power_3_4.last_changed) > 600) %}
            {{ false }}
          {% else %}
            {{ true }}
          {% endif %}
        {% else %}
        ??
        {% endif %}
    kajsa_asleep:
      friendly_name: Kajsa asleep
      entity_id: sensor.fibaro_system_fgwpef_wall_plug_gen5_power_2_4
      value_template: >
        {% if states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power_2_4 %}
          {% if states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power_2_4.state | float > 0.0 %}
            {{ true }}
          {% elif (as_timestamp(now()) - as_timestamp(states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power_2_4.last_changed) > 600) %}
            {{ false }}
          {% else %}
            {{ true }}
          {% endif %}
        {% else %}
        ??
        {% endif %}
