- platform: template
  sensors:
    living_room_motion_sensor_battery_low:
      entity_id: zwave.fibaro_system_fgms001zw5_motion_sensor_5
      value_template: '{{ states.zwave.fibaro_system_fgms001zw5_motion_sensor_5.attributes.battery_level < 10 }}'
