- platform: template
  sensors:
    living_room_motion_sensor_battery_low:
      entity_id: zwave.living_room_motion_sensor
      value_template: >
        {% if states.zwave.living_room_motion_sensor %}
        {{ states.zwave.living_room_motion_sensor.attributes.battery_level < 10 }}
        {% else %}
        ??
        {% endif %}
