- platform: trend
  sensors:
    hallway_camera_motion_detected:
      entity_id: sensor.captured_today_hallway
    living_room_camera_motion_detected:
      entity_id: sensor.captured_today_living_room
