- alias: Hallway lights on
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.hallway_cozy

- alias: Hallway lights off
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.hallway_off

- alias: Turn on hallway ceiling lamp when Arlo detects motion in hallway
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.hallway_ceiling_lamp
        transition: 2
        brightness_pct: >-
          {% if states.sensor.living_room_motion_sensor_luminance.state | int <= 20 %}
          20
          {% elif states.sensor.living_room_motion_sensor_luminance.state | int <= 100 %}
          {{ states.sensor.living_room_motion_sensor_luminance.state | int }}
          {% else %}
          100
          {% endif %}

- alias: Turn off hallway ceiling lamp when Arlo detects no motion in hallway
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'off'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: group.hallway_ceiling_lamp
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: group.hallway_ceiling_lamp
        transition: 10

- alias: Turn on left hallway ceiling lamp when Arlo detects motion in hallway at night
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway_lamp_left
        transition: 2
        brightness_pct: 1

- alias: Turn off hallway ceiling lamp when Arlo detects no motion in hallway at night
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: light.hallway_lamp_left
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: group.hallway_ceiling_lamp
        transition: 10
