- alias: Hallway lights on
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.hallway_cozy

- alias: Hallway lights off
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.hallway_off

- alias: Turn on hallway ceiling lamp when motion is detected in hallway
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.hallway_ceiling_lamp
        transition: 2
        brightness_pct: >-
          {% if states.sensor.living_room_motion_sensor_luminance.state | int <= 20 %}
          20
          {% elif states.sensor.living_room_motion_sensor_luminance.state | int <= 100 %}
          {{ states.sensor.living_room_motion_sensor_luminance.state | int }}
          {% else %}
          100
          {% endif %}

- alias: Turn off hallway ceiling lamp when no motion is detected in hallway
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'off'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: group.hallway_ceiling_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: group.hallway_ceiling_lamp
        transition: 10
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: group.hallway_ceiling_lamp

- alias: Turn on hallway ceiling lamp when main entrance is opened
  trigger:
    - platform: state
      entity_id: binary_sensor.main_entrance
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.hallway_ceiling_lamp
        transition: 2
        brightness_pct: >-
          {% if states.sensor.living_room_motion_sensor_luminance.state | int <= 20 %}
          20
          {% elif states.sensor.living_room_motion_sensor_luminance.state | int <= 100 %}
          {{ states.sensor.living_room_motion_sensor_luminance.state | int }}
          {% else %}
          100
          {% endif %}

- alias: Turn off hallway ceiling lamp when main entrance is closed if no light interior
  trigger:
    - platform: state
      entity_id: binary_sensor.main_entrance
      to: 'off'
      for: '00:03:00'
  condition:
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'off'
    - condition: state
      entity_id: group.hallway_ceiling_lamp
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: group.hallway_ceiling_lamp
        transition: 10
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: group.hallway_ceiling_lamp

- alias: Turn on left hallway ceiling lamp when motion is detected in hallway when someone asleep
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway_lamp_left
        transition: 2
        brightness_pct: 1

- alias: Turn off hallway ceiling lamp when no motion is detected in hallway when someone asleep
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: light.hallway_lamp_left
      state: 'on'
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway_lamp_left
        transition: 10
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: group.hallway_ceiling_lamp

- alias: Turn on hallway mood light instead of mirror lamp when one person goes to sleep
  trigger:
    - platform: state
      entity_id: group.sleep_status
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dc64de1a
        brightness_pct: 40
        rgb_color: [255,37,0]
    - service: switch.turn_off
      entity_id: switch.hallway_mirror_lamp_switch

- alias: Turn off hallway mood light when everyone asleep
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.gateway_light_7811dc64de1a
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dc64de1a

- alias: Turn on hallway mood light when motion is detected in hallway when everyone asleep
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dc64de1a
        brightness_pct: 40
        rgb_color: [255,37,0]

- alias: Turn off hallway mood light when no motion is detected in hallway when everyone asleep
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor
      to: 'off'
  condition:
    - condition: state
      entity_id: light.gateway_light_7811dc64de1a
      state: 'on'
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dc64de1a
