language: python
python:
  - "3.6"
before_install:
  - cp secrets.yaml-default secrets.yaml
  - touch ssl.crt ssl.key
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
