homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
    binary_sensor:
      homebridge_visible: true
    light:
      homebridge_visible: true
    scene:
      homebridge_visible: true

#introduction:

# discovery:

frontend:
  themes: !include themes.yaml

config:

updater:

conversation:

history:

logbook:

sun:

ios:

http:
  api_password: !secret http_password
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 2

apcupsd:
  host: localhost

tts:
  - platform: google

ifttt:
  key: !secret ifttt_key

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: samsungtv
    host: !secret samsungtv_host
    mac: !secret samsungtv_mac
    scan_interval: 20
  - platform: plex
    include_non_clients: true
    scan_interval: 10
    use_episode_art: true
  - platform: cast

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_host

tradfri:
  host: !secret tradfri_host

zwave:
  usb_path: /dev/ttyACM10
  network_key: !secret zwave_network_key
  new_entity_ids: true

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light

switch:
  - platform: flux
    lights:
      - light.bedroom_lamp
      - light.dining_room_lamp
      - light.living_room_lamp
      - light.living_room_star
      - light.hallway_lamp_left
      - light.hallway_lamp_middle
      - light.hallway_lamp_right
    name: Fluxer
    start_time: '8:00'
    stop_time: '22:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    disable_brightness_adjust: True
    mode: mired

light:
  - platform: yeelight
    devices:
      10.0.0.122:
        name: Kitchen Lightstrip
        transition: 1000
        use_music_mode: False
        save_on_change: False

device_tracker:
  - platform: asuswrt
    host: !secret asuswrt_host
    protocol: telnet
    username: !secret asuswrt_username
    password: !secret asuswrt_password
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

# influxdb:
#   host: !secret influxdb_host

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

deconz:
  host: !secret deconz_host
  api_key: !secret deconz_api_key

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: manual
    name: 'Alarm'
    code: !secret alarm_code
    pending_time: 60
    trigger_time: 120
    disarm_after_trigger: false
    armed_home:
      pending_time: 0
    armed_night:
      pending_time: 0
    armed_away:
      pending_time: 30
    triggered:
      pending_time: 60
  - platform: arlo

input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
scene: !include scenes.yaml
automation: !include_dir_merge_list automation
alert: !include_dir_merge_list alert
notify: !include_dir_merge_list notify
script: !include scripts.yaml
