homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ip_ban_enabled: true
  login_attempts_threshold: 5
  # base_url: example.duckdns.org:8123
  # ssl_certificate: /tbd
  # ssl_key: /tbd

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

apcupsd:
  host: localhost

# Weather Prediction
sensor:
  # - platform: yr
  #   monitored_conditions:
  #     - temperature
  #     - symbol
  #     - precipitation
  - platform: darksky
    api_key: !secret darksky_api_key
    update_interval: '00:30:00'
    monitored_conditions:
      - summary
      - minutely_summary
      - hourly_summary
      - daily_summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
  - platform: apcupsd
    resources:
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - itemp
  - platform: template
    sensors:
      johnnys_ipadminiretina_battery_level:
        friendly_name: Johnnys iPad Mini Retina Battery Level
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
            {%- if states.device_tracker.johnnysipadminiretina.attributes.battery %}
                {{ states.device_tracker.johnnysipadminiretina.attributes.battery|round }}
            {% else %}
                {{ states.sensor.johnnys_ipadminiretina_battery_level.state }}
            {%- endif %}
      johnnys_macbookpro_battery_level:
        friendly_name: Johnnys Macbook Pro Battery Level
        icon_template: mdi:laptop-mac
        unit_of_measurement: '%'
        value_template: >-
            {%- if states.device_tracker.johnnysmacbookpro.attributes.battery %}
                {{ states.device_tracker.johnnysmacbookpro.attributes.battery|round }}
            {% else %}
                {{ states.sensor.johnnys_macbookpro_battery_level.state }}
            {%- endif %}

binary_sensor:
  - platform: apcupsd

tts:
  - platform: google

# ios:

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: samsungtv
    host: !secret samsungtv_host
    mac: !secret samsungtv_mac

tradfri:
  host: !secret tradfri_host
  api_key: !secret tradfri_api_key

zwave:
  usb_path: /dev/ttyACM1

switch:
  platform: flux
  lights:
    - light.bedroom_lamp
    - light.dining_room_lamp
    - light.living_room_lamp
  name: Fluxer
  start_time: '7:00'
  stop_time: '22:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired

device_tracker:
  - platform: asuswrt
    host: !secret asuswrt_host
    protocol: telnet
    username: !secret asuswrt_username
    password: !secret asuswrt_password
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: !secret icloud_account_name

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_id_johnny
    - !secret telegram_id_kajsa

notify:
  - name: johnny
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_id_johnny
  - name: kajsa 
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_id_kajsa
  # - name: testfile
  #   platform: file
  #   filename: debug.log
  #   timestamp: True

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automation
