homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

#introduction:

discovery:

frontend:

config:

updater:

conversation:

history:

logbook:

sun:

ios:

http:
  api_password: !secret http_password
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

recorder:
  db_url: !secret recorder_db_url
  purge_days: 7

apcupsd:
  host: localhost

tts:
  - platform: google

media_player:
  # - platform: spotify
  #   client_id: !secret spotify_client_id
  #   client_secret: !secret spotify_client_secret
  - platform: samsungtv
    host: !secret samsungtv_host
    mac: !secret samsungtv_mac
    scan_interval: 20
  - platform: plex
    include_non_clients: true
    scan_interval: 5
    use_episode_art: true

tradfri:
  host: !secret tradfri_host
  api_key: !secret tradfri_api_key

zwave:
  usb_path: /dev/ttyACM10

switch:
  platform: flux
  lights:
    - light.bedroom_lamp
    - light.dining_room_lamp
    - light.living_room_lamp
  name: Fluxer
  start_time: '7:00'
  stop_time: '22:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired

device_tracker:
  - platform: asuswrt
    host: !secret asuswrt_host
    protocol: telnet
    username: !secret asuswrt_username
    password: !secret asuswrt_password
  # - platform: icloud
  #   username: !secret icloud_username
  #   password: !secret icloud_password
  #   account_name: !secret icloud_account_name

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_id_johnny
    - !secret telegram_id_kajsa

influxdb:
  host: !secret influxdb_host

# android_ip_webcam:
#   host: !secret android_webcam_host
#   # username: !secret android_webcam_username
#   # password: !secret android_webcam_password
#   motion_sensor: true
#   name: Living Room Camera

# arlo:
#   username: !secret arlo_username
#   password: !secret arlo_password

# camera:
#   - platform: arlo

input_boolean: !include input_boolean.yaml
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
scene: !include scenes.yaml
automation: !include_dir_merge_list automation
alert: !include_dir_merge_list alert
notify: !include_dir_merge_list notify
