homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

recorder:
  db_url: !secret recorder_db_url
  purge_days: 7

# View all events in a logbook
logbook:

# Track the sun
sun:

apcupsd:
  host: localhost

tts:
  - platform: google

ios:

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: samsungtv
    host: !secret samsungtv_host
    mac: !secret samsungtv_mac
  - platform: plex
    include_non_clients: true
    scan_interval: 10
    use_episode_art: true

tradfri:
  host: !secret tradfri_host
  api_key: !secret tradfri_api_key

zwave:
  usb_path: /dev/ttyACM10

switch:
  platform: flux
  lights:
    - light.bedroom_lamp
    - light.dining_room_lamp
    - light.living_room_lamp
  name: Fluxer
  start_time: '7:00'
  stop_time: '22:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired

device_tracker:
  - platform: asuswrt
    host: !secret asuswrt_host
    protocol: telnet
    username: !secret asuswrt_username
    password: !secret asuswrt_password
  # - platform: icloud
  #   username: !secret icloud_username
  #   password: !secret icloud_password
  #   account_name: !secret icloud_account_name

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_id_johnny
    - !secret telegram_id_kajsa

sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
group: !include groups.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automation
alert: !include_dir_merge_list alert
notify: !include_dir_merge_list notify
