### GROUPS:VIEWS ###

default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.household
    - group.living_room
    - group.bedroom

lights:
  name: Lights
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.interior_lights
    # - group.exterior_lights
    - switch.fluxer

living:
  name: Living Room
  view: yes
  icon: mdi:sofa
  entities:
    - group.living_room
    - media_player.samsung_tv_remote
    - media_player.spotify
    - media_player.xboxone

bed:
  name: Bedroom
  view: yes
  icon: mdi:hotel
  entities:
    - group.bedroom

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.automations
    - group.scenes

devices:
  name: Devices
  view: yes
  icon: mdi:cellphone-link
  entities:
    - group.household
    - group.ups_status
    - group.device_status

sensors:
    name: Sensors
    view: yes
    icon: mdi:gauge
    entities:
      - group.battery_levels
      - group.indoor_temperature

weatherdash:
  name: Weather
  view: yes
  icon: mdi:weather-sunset
  entities:
    - group.weather_summary
    - group.weather

### GROUPS:COLLECTIONS ###

Interior Lights:
  - group.living_room_lights
  - group.bedroom_lights

Living Room:
  - light.dining_room_lamp
  - light.living_room_lamp
  - switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3_0
  - binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_5_0
  - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature_5_1
  - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance_5_3
  - sensor.plex

Bedroom:
  - light.bedroom_lamp
  - switch.fibaro_system_fgwpef_wall_plug_gen5_switch_2_0

### GROUPS:ROOMS ###

Living Room Lights:
  icon: mdi:sofa
  entities:
    - light.dining_room_lamp
    - light.living_room_lamp

Bedroom Lights:
  icon: mdi:hotel
  entities:
    - light.bedroom_lamp

### GROUPS:SPECIAL ###

Automations:
  - automation.fluxer_switch_on_by_default
  - automation.lights__lead_lights_when_arriving_late
  - automation.lights__turn_off_lights_when_everyone_are_away
  - automation.lights__turn_off_lights_when_going_to_bed
  - automation.lights__turn_on_lights_in_the_evening_if_home

Household:
  - device_tracker.johnnysiphone
  - device_tracker.kajsasiphone

Scenes:
  - scene.bright
  - scene.day
  - scene.dinner
  - scene.evening
  - scene.good_morning
  - scene.good_night
  - scene.movie
  - scene.night
  - scene.bedroom_dimmed

Device Status:
  - sensor.johnnys_iphone_battery_level
  - sensor.johnnys_iphone_battery_state
  - sensor.kajsas_iphone_battery_level
  - sensor.kajsas_iphone_battery_state

UPS Status:
  - binary_sensor.ups_online_status
  - sensor.ups_battery
  - sensor.ups_input_voltage
  - sensor.ups_internal_temperature
  - sensor.ups_load
  - sensor.ups_status
  - sensor.ups_time_left

Battery Levels:
  - sensor.ups_battery
  - sensor.living_room_motion_sensor_battery

Indoor Temperature:
  - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature_5_1

Weather:
  - sun.sun
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_cloud_coverage
  - sensor.dark_sky_dew_point
  - sensor.dark_sky_humidity
  - sensor.dark_sky_icon
  - sensor.dark_sky_nearest_storm_bearing
  - sensor.dark_sky_nearest_storm_distance
  - sensor.dark_sky_ozone
  - sensor.dark_sky_precip
  - sensor.dark_sky_precip_intensity
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_pressure
  - sensor.dark_sky_temperature
  - sensor.dark_sky_visibility
  - sensor.dark_sky_wind_bearing
  - sensor.dark_sky_wind_speed
  - sensor.dark_sky_temperature_max
  - sensor.dark_sky_temperature_min
  - sensor.dark_sky_apparent_temperature_max
  - sensor.dark_sky_apparent_temperature_min
  - sensor.dark_sky_precip_intensity_max

Weather Summary:
  - sensor.dark_sky_summary
  - sensor.dark_sky_minutely_summary
  - sensor.dark_sky_hourly_summary
  - sensor.dark_sky_daily_summary
