- alias: Toggle sleep on for Johnny
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_johnny_charger_power
      above: 1
  condition:
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.johnny_asleep

- alias: Toggle sleep on for Kajsa
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_kajsa_charger_power
      above: 1
  condition:
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kajsa_asleep

- alias: Toggle sleep off for Johnny
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_johnny_charger_power
      below: 1
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.johnny_asleep

- alias: Toggle sleep off for Kajsa
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_kajsa_charger_power
      below: 1
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.kajsa_asleep

- alias: Toggle all asleep on
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: and
      conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.johnnysiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.johnny_asleep
                state: 'on'
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'not_home'
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.kajsasiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.kajsa_asleep
                state: 'on'
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'not_home'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.everyone_asleep

- alias: Toggle all asleep off
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'off'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.everyone_asleep
