- alias: Toggle sleep on for Johnny
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_johnny_charger_power
      above: 1
  condition:
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.johnny_asleep

- alias: Toggle sleep on for Kajsa
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_kajsa_charger_power
      above: 1
  condition:
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kajsa_asleep

- alias: Toggle sleep off for Johnny
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_johnny_charger_power
      below: 1
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.johnny_asleep

- alias: Toggle sleep off for Kajsa
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_kajsa_charger_power
      below: 1
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.kajsa_asleep
