- alias: Bedroom lights on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_normal

- alias: Bedroom lights off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedroom lights dimmed when one person goes to bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: or
      conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.johnnysiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.johnny_asleep
                state: 'off'
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'not_home'
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.kajsasiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.kajsa_asleep
                state: 'off'
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_cozy
