- alias: Bedroom lights on
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_cozy

- alias: Bedroom lights off
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedroom lights dimmed when one person goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.all_asleep
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_cozy

- alias: Bedroom lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal

- alias: Living room lights cozy when empty
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_cozy
