- alias: Bedroom lights on
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  condition:
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_cozy

- alias: Bedroom lights off
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedroom lights dimmed when one person goes to bed
  trigger:
    - platform: state
      entity_id: group.sleep_status
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_cozy

- alias: Bedroom lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_normal

- alias: Bedroom lights cozy when empty
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.light_interior
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_cozy
