- alias: Turn on Johnnys chargers when home
  trigger:
    - platform: state
      entity_id: device_tracker.johnnysiphone
      to: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.bedroom_johnny_charger_switch

- alias: Turn off Johnnys chargers when not home
  trigger:
    - platform: state
      entity_id: device_tracker.johnnysiphone
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_johnny_charger_switch

- alias: Turn on Kajsas chargers when home
  trigger:
    - platform: state
      entity_id: device_tracker.kajsasiphone
      to: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.bedroom_kajsa_charger_switch

- alias: Turn off Kajsas chargers when not home
  trigger:
    - platform: state
      entity_id: device_tracker.kajsasiphone
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_kajsa_charger_switch
