- alias: Turn off chromecast when Harmony input not music
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Music'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.living_room_speakers
