- alias: Living room lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_cozy

- alias: Living room lights off
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_off

- alias: Living room lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal

- alias: Living room lights cozy when empty
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor_sensor
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_cozy
