# switch test automation
- alias: Toggle living room motion sensor on click
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001d6208c # living room light switch
        click_type: single
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.living_room_motion_detection_enabled
