- alias: Kitchen lights on
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_cozy

- alias: Kitchen lights off
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_off
