- alias: Kitchen lights on
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_cozy

- alias: Kitchen lights off
  trigger:
    platform: state
    entity_id: input_boolean.light_interior
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_off

- alias: Kitchen lights on full when motion
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_full

- alias: Kitchen lights cozy when no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      to: 'off'
      for: '00:03:00'
  condition:
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_cozy
