- alias: Disable kitchen motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_dimmer
        event: 2000
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_dimmer
        event: 3000
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_dimmer
        event: 4000
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_motion_detection_enabled

- alias: Enable kitchen motion
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for: '00:10:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_dimmer
        event: 1000
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.kitchen_motion_detection_enabled
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.light_mode', 'on') %}
          scene.kitchen_idle
          {% else %}
          scene.kitchen_off
          {% endif %}
