default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.alarm
    - group.household
    - group.interior_lights
    - group.scenes
    - group.indoor_temperature

living:
  name: Living Room
  view: yes
  icon: mdi:sofa
  entities:
    - group.living_room_lights
    - group.living_room
    - media_player.samsung_tv_remote
    - media_player.spotify
    - media_player.xboxone
    - media_player.tv_ue55f8000
    - media_player.living_room_speakers

kitch:
  name: Kitchen
  view: yes
  icon: mdi:stove
  entities:
    - group.kitchen
    - group.kitchen_lights

bed:
  name: Bedroom
  view: yes
  icon: mdi:hotel
  entities:
    - group.bedroom_lights
    - group.bedroom
    - group.sleep_status

hall:
  name: Hallway
  view: yes
  icon: mdi:cube-unfolded
  entities:
    - group.hallway_lights
    - group.hallway_ceiling_lamp
    - group.hallway

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.light_automation
    - group.security_automation

security:
  name: Security
  view: yes
  icon: mdi:cctv
  entities:
    - group.hallway_camera
    - group.living_room_camera

sensors:
    name: Sensors
    view: yes
    icon: mdi:gauge
    entities:
      - group.ups_status
      - group.battery_levels
      - group.power_usage
      - group.zwave

weatherdash:
  name: Weather
  view: yes
  icon: mdi:weather-sunset
  entities:
    - group.weather_summary
    - group.weather
