default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.household
    - group.living_room
    - group.bedroom

lights:
  name: Lights
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.interior_lights
    # - group.exterior_lights
    - group.scenes

living:
  name: Living Room
  view: yes
  icon: mdi:sofa
  entities:
    - group.living_room
    - media_player.samsung_tv_remote
    - media_player.spotify
    - media_player.xboxone
    - media_player.tv_ue55f8000

bed:
  name: Bedroom
  view: yes
  icon: mdi:hotel
  entities:
    - group.bedroom

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - switch.fluxer
    - group.alarm
    - group.light_automation
    - group.security_automation

security:
  name: Security
  view: yes
  icon: mdi:security-home
  entities:
    - group.hallway_camera
    - group.living_room_camera
    - group.alarm

sensors:
    name: Sensors
    view: yes
    icon: mdi:gauge
    entities:
      - group.ups_status
      - group.battery_levels
      - group.indoor_temperature
      - group.zwave

weatherdash:
  name: Weather
  view: yes
  icon: mdi:weather-sunset
  entities:
    - group.weather_summary
    - group.weather
