- platform: template
  sensors:
    living_room_motion_sensor_battery:
      friendly_name: Living Room Motion Sensor
      entity_id: zwave.fibaro_system_fgms001zw5_motion_sensor_5
      icon_template: mdi:battery
      value_template: >-
        {%- if states.zwave.fibaro_system_fgms001zw5_motion_sensor_5 -%}
          {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor_5.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_smoke_sensor_battery:
      friendly_name: Living Room Smoke Sensor
      entity_id: zwave.fibaro_system_fgsd002_smoke_sensor_6
      icon_template: mdi:battery
      value_template: >-
        {%- if states.zwave.fibaro_system_fgsd002_smoke_sensor_6 -%}
          {{ states.zwave.fibaro_system_fgsd002_smoke_sensor_6.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_camera_battery:
      friendly_name: Living Room Camera Battery
      entity_id: camera.living_room
      icon_template: mdi:battery
      value_template: >-
        {%- if camera.living_room -%}
          {{ camera.living_room.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
    hallway_camera_battery:
      friendly_name: Hallway Camera Battery
      entity_id: camera.hallway
      icon_template: mdi:battery
      value_template: >-
        {%- if camera.hallway -%}
          {{ camera.hallway.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
