- platform: template
  sensors:
    living_room_motion_sensor_battery:
      friendly_name: Living Room Motion Sensor
      icon_template: mdi:battery
      value_template: >-
        {%- if states.zwave.living_room_motion_sensor -%}
          {{ states.zwave.living_room_motion_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_smoke_sensor_battery:
      friendly_name: Living Room Smoke Sensor
      icon_template: mdi:battery
      value_template: >-
        {%- if states.zwave.hallway_smoke_sensor -%}
          {{ states.zwave.hallway_smoke_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_camera_battery:
      friendly_name: Living Room Camera Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.camera.living_room -%}
          {{ states.camera.living_room.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    hallway_camera_battery:
      friendly_name: Hallway Camera Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.camera.hallway -%}
          {{ states.camera.hallway.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    kitchen_motion_sensor_battery:
      friendly_name: Kitchen Motion Sensor Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.kitchen_motion_sensor -%}
          {{ states.binary_sensor.kitchen_motion_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    hallway_motion_sensor_battery:
      friendly_name: Hallway Motion Sensor Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.hallway_motion_sensor -%}
          {{ states.binary_sensor.hallway_motion_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    bedroom_window_battery:
      friendly_name: Bedroom Window Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.bedroom_window -%}
          {{ states.binary_sensor.bedroom_window.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_right_window_small_battery:
      friendly_name: Living Room Right Window Small Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.living_room_right_window_small -%}
          {{ states.binary_sensor.living_room_right_window_small.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_left_window_large_battery:
      friendly_name: Living Room Left Window Large Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.living_room_left_window_large -%}
          {{ states.binary_sensor.living_room_left_window_large.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    main_entrance_battery:
      friendly_name: Main Entrance Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.main_entrance -%}
          {{ states.binary_sensor.main_entrance.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    patio_entrance_battery:
      friendly_name: Patio Entrance Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.patio_entrance -%}
          {{ states.binary_sensor.patio_entrance.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    bedroom_temperature_battery:
      friendly_name: Bedroom Temperature Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.sensor.bedroom_environment_temperature -%}
          {{ states.sensor.bedroom_environment_temperature.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    bathroom_temperature_battery:
      friendly_name: Bathroom Temperature Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.sensor.bathroom_environment_temperature -%}
          {{ states.sensor.bathroom_environment_temperature.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_light_switch_battery:
      friendly_name: Living Room Light Switch Battery
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.switch_158d0001d6208c -%}
          {{ states.binary_sensor.switch_158d0001d6208c.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
