- platform: template
  sensors:
    living_room_motion_sensor_battery:
      friendly_name: Living Room Motion Sensor
      entity_id: zwave.living_room_motion_sensor
      icon_template: mdi:battery
      value_template: >-
        {%- if states.zwave.living_room_motion_sensor -%}
          {{ states.zwave.living_room_motion_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_smoke_sensor_battery:
      friendly_name: Living Room Smoke Sensor
      entity_id: zwave.hallway_smoke_sensor
      icon_template: mdi:battery
      value_template: >-
        {%- if states.zwave.hallway_smoke_sensor -%}
          {{ states.zwave.hallway_smoke_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_camera_battery:
      friendly_name: Living Room Camera Battery
      entity_id: camera.living_room
      icon_template: mdi:battery
      value_template: >-
        {%- if states.camera.living_room -%}
          {{ states.camera.living_room.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    hallway_camera_battery:
      friendly_name: Hallway Camera Battery
      entity_id: camera.hallway
      icon_template: mdi:battery
      value_template: >-
        {%- if states.camera.hallway -%}
          {{ states.camera.hallway.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    kitchen_motion_sensor_battery:
      friendly_name: Kitchen Motion Sensor Battery
      entity_id: binary_sensor.kitchen_motion_sensor
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.kitchen_motion_sensor -%}
          {{ states.binary_sensor.kitchen_motion_sensor.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_right_window_large_battery:
      friendly_name: Living Room Right Window Large Battery
      entity_id: binary_sensor.living_room_right_window_large
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.living_room_right_window_large -%}
          {{ states.binary_sensor.living_room_right_window_large.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
    living_room_right_window_small_battery:
      friendly_name: Living Room Right Window Small Battery
      entity_id: binary_sensor.living_room_right_window_small
      icon_template: mdi:battery
      value_template: >-
        {%- if states.binary_sensor.living_room_right_window_small -%}
          {{ states.binary_sensor.living_room_right_window_small.attributes.battery_level }}
        {%- else -%}
          101
        {%- endif -%}
      unit_of_measurement: '%'
