- alias: Notify movement if no one is home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_5_0
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
  action:
    - service: notify.all_phones
      data:
        message: "Movement detected at home!"
        data:
          attachment:
            url: !secret android_webcam_photo_url
            hide-thumbnail: false

# TODO: Add condition guest mode = off when implemented
- alias: Turn on vacation mode when away for 24h
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      state: 'no_home'
      for:
        hours: 24
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode

- alias: Turn off vacation mode when coming home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
