- alias: Arm alarm when away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.alarm_mode
    state: 'on'
  action:
    - service: camera.enable_motion_detection
      entity_id: camera.hallway
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Disarm alarm when home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_mode
    state: 'on'
  action:
    - service: camera.disable_motion_detection
      entity_id: camera.hallway
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code
    - service: tts.google_say
      entity_id: media_player.living_room_speakers
      data_template:
        message: 'Welcome home. The alarm has been turned off.'

- alias: Turn on lights and notify when motion detected
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_motion_detected
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        title: "Movement detected at home!"
        message: "Movement detected but nobody is home."
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Reset alarm 10 minutes after motion detected
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_motion_detected
      to: 'on'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.alarm_motion_detected

- alias: Turn on vacation mode when away for 24h
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
      for:
        hours: 24
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - service: notify.all_phones
      data:
        title: "Vacation mode enabled"
        message: "Set Arlo to vacation mode manually to activate siren."

- alias: Turn off vacation and guest mode when coming home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode
