# Actions for different alarm states
- alias: Alarm armed away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
  action:
    - service: notify.all_phones
      data:
        title: "Alarm has been armed"
        message: "The alarm has been set to armed_away"
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home
    - service: scene.turn_on
      entity_id: scene.lights_off
    - service: input_select.select_option
      data:
        entity_id: input_select.harmony
        option: 'PowerOff'

- alias: Alarm disarmed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'disarmed'
  action:
    - service: notify.all_phones
      data:
        title: "Alarm has been disarmed"
        message: "The alarm has been set to disarmed"
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.home
    # - service: remote.turn_on
    #   entity_id: remote.living_room
    #   data:
    #     activity: 29561682
    # - delay:
    #     seconds: 5
    # - service: tts.google_say
    #   entity_id: media_player.living_room_speakers
    #   data:
    #     message: 'Welcome home. The alarm has been turned off.'
    # - service: remote.turn_on
    #   entity_id: remote.living_room
    #   data:
    #     activity: -1

- alias: Alarm triggered
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        title: "Movement detected at home!"
        message: "Check camera recording immediately."

# Automatically enable / disable alarm
- alias: Automatically arm alarm when away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.alarm_mode
    state: 'on'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Automatically disarm alarm when home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_mode
    state: 'on'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Automatically arm alarm home when last person goes to sleep
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'home'
          - condition: state
            entity_id: input_boolean.johnny_asleep
            state: 'on'
      - condition: state
        entity_id: device_tracker.johnnysiphone
        state: 'not_home'
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'home'
          - condition: state
            entity_id: input_boolean.kajsa_asleep
            state: 'on'
      - condition: state
        entity_id: device_tracker.kajsasiphone
        state: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Automatically disarm alarm when not sleeping
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'off'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'off'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

# Handle automatic vacation mode
- alias: Turn on vacation mode when away for 24h
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
      for:
        hours: 24
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - service: notify.all_phones
      data:
        title: "Vacation mode enabled"
        message: "Set Arlo to vacation mode manually to activate siren."

- alias: Turn off vacation and guest mode when coming home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode
