- alias: Reset living room arlo motion boolean when triggered
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_arlo_motion
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_arlo_motion

- alias: Reset living room arlo motion boolean when triggered
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_arlo_motion
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_arlo_motion

- alias: Trigger alarm when Arlo detects motion in living room
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_arlo_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

- alias: Trigger alarm when Arlo detects motion in hallway
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_arlo_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

- alias: Turn on hallway ceiling lamp when Arlo detects motion in hallway
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_arlo_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'disarmed'
  action:
    - service: light.turn_on
      data:
        entity_id: group.hallway_ceiling_lamp
        brightness_pct: 50
        transition: 5
    - service: light.turn_off
      data:
        entity_id: group.hallway_ceiling_lamp
        transition: 30
