- alias: Check if ok if no movement but home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_5_0
      to: 'off'
      for:
        hours: 4
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
      for:
        minutes: 10
    - condition: state
      entity_id: binary_sensor.kajsa_asleep
      state: 'off'
      for:
        minutes: 10
    - condition: state
      entity_id: binary_sensor.johnny_asleep
      state: 'off'
      for:
        minutes: 10
  action:
    - service: notify.all_phones
      data:
        message: "Someone home, but no movement detected!"
