# - alias: Fluxer switch on by default
#   initial_state: 'on'
#   trigger: 
#     platform: event
#     event: zwave.network_ready
#   action:
#     service: homeassistant.turn_on
#     entity_id: switch.fluxer

- alias: Lights - Turn on lights if home and dark
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance_5_3
      below: 40
    - platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'
        - condition: time
          after: '06:00:00'
          before: '23:00:00'
        - condition: numeric_state
          entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance_5_3
          below: 40
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Lights - Turn off lights when everyone are away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights

- alias: Lights - Lead lights when arriving late
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.dining_room_lamp

- alias: Lights - Turn off lights when going to bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.johnnys_iphone_battery_state
      from: 'Unplugged'
      to: 'Charging'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.night

- alias: Lights - Dim bedroom lights when K going to bed but J up
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.kajsas_iphone_battery_state
      from: 'Unplugged'
      to: 'Charging'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: device_tracker.johnnysiphone
        state: 'home'
      - condition: state
        entity_id: sensor.johnnys_iphone_battery_state
        state: 'Unplugged'
      - condition: state
        entity_id: light.bedroom_light
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_dimmed

- alias: Lights - Dim bedroom lights when J going to bed but K up
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.johnnys_iphone_battery_state
      from: 'Unplugged'
      to: 'Charging'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: device_tracker.kajsasiphone
        state: 'home'
      - condition: state
        entity_id: sensor.kajsas_iphone_battery_state
        state: 'Unplugged'
      - condition: state
        entity_id: light.bedroom_light
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_dimmed

# - alias: Lights - Lead lights during the night if motion detected
#   initial_state: 'on'
#   trigger:
#     platform: state
#     entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_5_0
#     from: 'off'
#     to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: time
#         after: '22:00:00'
#         before: '06:00:00'
#       - condition: or
#         conditions:
#           - condition: state
#             entity_id: device_tracker.johnnysiphone
#             state: 'home'
#           - condition: state
#             entity_id: device_tracker.kajsasiphone
#             state: 'home'
#   action:
#     service: homeassistant.turn_on
#     entity_id: light.dining_room_lamp

