- alias: Fluxer switch on by default
  initial_state: 'on'
  trigger: 
    platform: homeassistant
    event: start
  action:
    service: homeassistant.turn_on
    entity_id: switch.fluxer

- alias: Lights - Turn on lights in the evening if home
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-02:00:00'
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Lights - Turn off lights when everyone are away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights

- alias: Lights - Lead lights when arriving late
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
    for:
      minutes: 10
  condition:
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.dining_room_lamp
