- alias: Fluxer switch on by default
  initial_state: 'on'
  trigger: 
    platform: event
    event_type: zwave.network_ready
  action:
    service: homeassistant.turn_on
    entity_id: switch.fluxer

- alias: Lights on when home
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance_5_3
      below: 40
      # for:
      #   minutes: 10
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '06:00:00'
      before: '23:00:00'
    - condition: numeric_state
      entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance_5_3
      below: 40
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_on

- alias: Lights off when bright
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance_5_3
      above: 40
      # for:
      #   minutes: 10
  condition:
    - condition: time
      after: '06:00:00'
      before: '23:00:00'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off

- alias: Lights off when away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      state: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off

- alias: Lights on when arriving late
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.johnnysiphone
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.kajsasiphone
      from: 'not_home'
      to: 'home'
  condition:
    - condition: and
      conditions:
        - condition: time
          after: '23:00:00'
          before: '06:00:00'
        - condition: state
          entity_id: group.household
          state: 'home'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.dining_room_lamp

- alias: Lights off when last person goes to bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.johnny_asleep
      state: 'on'
    - platform: state
      entity_id: binary_sensor.kajsa_asleep
      state: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.johnnysiphone
                state: 'home'
              - condition: state
                entity_id: binary_sensor.johnny_asleep
                state: 'on'
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'not_home'
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.kajsasiphone
                state: 'home'
              - condition: state
                entity_id: binary_sensor.kajsa_asleep
                state: 'on'
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.lights_off

- alias: Bedroom lights dimmed when one person goes to bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kajsa_asleep
      state: 'on'
    - platform: state
      entity_id: binary_sensor.johnny_asleep
      state: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.johnnysiphone
                state: 'home'
              - condition: state
                entity_id: binary_sensor.johnny_asleep
                state: 'off'
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'not_home'
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.kajsasiphone
                state: 'home'
              - condition: state
                entity_id: binary_sensor.kajsa_asleep
                state: 'off'
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_cozy

- alias: Lights on when on vacation
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.lights_vacation

- alias: Turn off lights when on vacation
  initial_state: 'on'
  trigger:
    platform: time
    after: '22:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.lights_off

- alias: Living Room lights dimmed when watching TV
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.xboxone
      to: 'playing'
    - platform: state
      entity_id: media_player.tv_ue55f8000
      to: 'playing'
  condition:
    - condition: state
      entity_id: light.living_room_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_cozy

- alias: Living Room restore lights when not watching TV
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.xboxone
      from: 'playing'
    - platform: state
      entity_id: media_player.tv_ue55f8000
      from: 'playing'
  condition:
    - condition: state
      entity_id: light.living_room_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_on

# - alias: Lights - Lead lights during the night if motion detected
#   initial_state: 'on'
#   trigger:
#     platform: state
#     entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_5_0
#     from: 'off'
#     to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: time
#         after: '22:00:00'
#         before: '06:00:00'
#       - condition:
#         - condition: state
#           entity_id: group.household
#           state: 'home'
#       - condition:
#           condition: state
#           entity_id: group.living_room_lights
#           state: 'off'
#   action:
#     service: homeassistant.turn_on
#     entity_id: light.dining_room_lamp
