- alias: Set Harmony activity using input_select
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
  action:
    service: remote.turn_on
    entity_id: remote.living_room
    data_template:
      activity: >
        {% if is_state("input_select.harmony", "Watch TV") %}
          29557158
        {% elif is_state("input_select.harmony", "Watch Movies") %}
          29557640
        {% else %}
          -1
        {% endif %}

- alias: Update Harmony input_select
  hide_entity: True
  trigger:
    platform: state
    entity_id: remote.living_room
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.harmony
      option: "{{ states.remote.living_room.attributes.current_activity }}"
