- alias: Notify and turn on lights when smoke detected
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.fibaro_system_fgsd002_smoke_sensor_smoke_6_1
      to: '255'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        message: "Smoke detected at home!"
