- alias: Notify and turn on lights when smoke detected
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.fibaro_system_fgsd002_smoke_sensor_smoke_6_1
      to: '255'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        title: "Smoke detected at home!"
        message: "Please contact anyone at home or fire department."

- alias: Notify and turn on lights when excessive heat detected
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.fibaro_system_fgsd002_smoke_sensor_heat_6_4
      to: '255'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        title: "Excessive heat detected at home!"
        message: "Please contact anyone at home or fire department."
