# Actions for different alarm states
- alias: Alarm armed away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
  action:
    - service: notify.all_phones
      data:
        title: "Alarm has been armed"
        message: "The alarm has been set to armed_away"
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dc64de1a
        brightness_pct: 100
        rgb_color: [255,0,0]
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dc64de1a

- alias: Alarm disarmed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'disarmed'
  action:
    - service: notify.all_phones
      data:
        title: "Alarm has been disarmed"
        message: "The alarm has been set to disarmed"
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dc64de1a
        brightness_pct: 100
        rgb_color: [0,255,0]
    - delay: '00:00:10'
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dc64de1a

- alias: Alarm triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        title: '** Home Alarm Triggered **'
        message: 'Check camera recording immediately'
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dc64de1a
        brightness_pct: 100
        rgb_color: [255,0,0]

- alias: Alarm pending
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: 'armed_away'
      to: 'pending'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dc64de1a
        brightness_pct: 100
        rgb_color: [255,255,0]

# Automatically enable / disable alarm
- alias: Automatically arm alarm when away
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.alarm_mode
    state: 'on'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Automatically disarm alarm when home
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_mode
    state: 'on'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Automatically arm alarm home when last person goes to sleep
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'home'
          - condition: state
            entity_id: input_boolean.johnny_asleep
            state: 'on'
      - condition: state
        entity_id: device_tracker.johnnysiphone
        state: 'not_home'
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'home'
          - condition: state
            entity_id: input_boolean.kajsa_asleep
            state: 'on'
      - condition: state
        entity_id: device_tracker.kajsasiphone
        state: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Automatically disarm alarm when not sleeping
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'off'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

# Handle automatic vacation mode
- alias: Turn on vacation mode when away for 24h
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
      for:
        hours: 24
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - service: notify.all_phones
      data:
        title: "Vacation mode enabled"
        message: "Set Arlo to vacation mode manually to activate siren."

- alias: Turn off vacation mode when coming home
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode

# Alarm triggers
- alias: Trigger alarm when perimiter breached when armed_night
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_entrance
        - binary_sensor.patio_entrance
        - binary_sensor.bedroom_window
        - binary_sensor.living_room_window_right
        - binary_sensor.living_room_window_left
        - binary_sensor.bathroom_window
        - binary_sensor.guest_bedroom_window
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_night'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

- alias: Trigger alarm when perimiter breached when armed_away
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_entrance
        - binary_sensor.patio_entrance
        - binary_sensor.bedroom_window
        - binary_sensor.living_room_window_left
        - binary_sensor.living_room_window_right
        - binary_sensor.bathroom_window
        - binary_sensor.guest_bedroom_window
      to: 'on'
    - platform: state
      entity_id:
        - sensor.last_living_room
        - sensor.last_hallway
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

- alias: Trigger alarm when motion detected when armed_away and vacation
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bedroom_motion_sensor
        - binary_sensor.hallway_motion_sensor
        - binary_sensor.kitchen_motion_sensor
        - binary_sensor.living_room_motion_sensor_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
    - condition: state
      entity_id: input_binary.vacation_mode
      state: 'on'
    - condition: state
      entity_id: input_binary.guest_mode
      state: 'off'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
