- alias: Lights on when home
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_motion_sensor_luminance
      below: 40
      for:
        minutes: 10
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: group.sleep_status
      to: 'off'
  condition:
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
    - condition: numeric_state
      entity_id: sensor.living_room_motion_sensor_luminance
      below: 40
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_normal

- alias: Lights off when bright
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_motion_sensor_luminance
      above: 40
      for:
        minutes: 10
  condition:
    - condition: time
      after: '06:00:00'
      before: '23:00:00'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off

- alias: Lights off when away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off

- alias: Lights on when arriving late
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.johnnysiphone
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.kajsasiphone
      from: 'not_home'
      to: 'home'
  condition:
    - condition: and
      conditions:
        - condition: time
          after: '23:00:00'
          before: '06:00:00'
        - condition: state
          entity_id: group.household
          state: 'home'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.dining_room_lamp

- alias: Lights off when last person goes to bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
      for:
        minutes: 1
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: and
      conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.johnnysiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.johnny_asleep
                state: 'on'
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'not_home'
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.kajsasiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.kajsa_asleep
                state: 'on'
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.lights_off

- alias: Bedroom lights dimmed when one person goes to bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: or
      conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.johnnysiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.johnny_asleep
                state: 'off'
          - condition: state
            entity_id: device_tracker.johnnysiphone
            state: 'not_home'
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: device_tracker.kajsasiphone
                state: 'home'
              - condition: state
                entity_id: input_boolean.kajsa_asleep
                state: 'off'
          - condition: state
            entity_id: device_tracker.kajsasiphone
            state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_cozy

- alias: Lights on when on vacation
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      at: '18:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.lights_vacation

- alias: Turn off lights when on vacation
  initial_state: 'on'
  trigger:
    - platform: time
      at: '22:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.lights_off

- alias: Set lights to cozy after 10pm if on
  initial_state: 'on'
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: state
      entity_id: group.interior_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.light_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.lights_cozy
