- alias: Home lights on
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_motion_sensor_luminance
      below: 40
      for:
        minutes: 10
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'off'
    - platform: state
      entity_id:
        - binary_sensor.kitchen_motion_sensor
        - binary_sensor.living_room_motion_sensor_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: 'disarmed'
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: 'armed_night'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_room_motion_sensor_luminance
      below: 40
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.lights_needed

- alias: Home lights off
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
    - platform: numeric_state
      entity_id: sensor.living_room_motion_sensor_luminance
      above: 40
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lights_needed

- alias: Home lights on when alarm triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full

- alias: Home lights off after alarm triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: 'triggered'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off

- alias: Lights dimmed when last person goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.bedroom_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_cozy

- alias: Lights off when last person goes to bed after one minute
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lights_needed

- alias: Lights off when at night when no one home
  trigger:
    - platform: time
      at: '22:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'not_home'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off

- alias: Lights on when not home
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      at: '17:30:00'
  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_vacation
