- alias: Set Harmony activity using input_select
  trigger:
    platform: state
    entity_id: input_select.harmony
  action:
    service: remote.turn_on
    entity_id: remote.living_room
    data_template:
      activity: >
        {% if is_state("input_select.harmony", "TV") %}
          29557158
        {% elif is_state("input_select.harmony", "Movies") %}
          29561843
        {% elif is_state("input_select.harmony", "Music") %}
          29561682
        {% else %}
          -1
        {% endif %}

- alias: Update Harmony input_select
  trigger:
    platform: state
    entity_id: remote.living_room
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.harmony
      option: "{{ states.remote.living_room.attributes.current_activity }}"


# 2017-11-30 08:26:09 ERROR (SyncWorker_2) [homeassistant.components.remote.harmony] Missing required argument: device
# - alias: Turn TV sound on when switching to TV mode
#   trigger:
#     platform: state
#     entity_id: input_select.harmony
#     to: 'TV'
#   action:
#     service: remote.send_command
#     data:
#       entity_id: remote.living_room
#       command: VolumeUp
#       num_repeats: 10

# - alias: Turn TV sound off when switching from TV mode
#   trigger:
#     platform: state
#     entity_id: input_select.harmony
#     from: 'TV'
#   action:
#     service: remote.send_command
#     data:
#       entity_id: remote.living_room
#       command: VolumeDown
#       num_repeats: 30
