- alias: Toggle guest asleep on
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_asleep
        event: 1000
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.guest_asleep
