- alias: Guest Bedroom lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion_sensor
      to: 'off'
      for:
        minutes: 10
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
    # - condition: state
    #   entity_id: group.sleep_status
    #   state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_bedroom_cozy

- alias: Guest Bedroom lights off
  trigger:
    platform: state
    entity_id: input_boolean.lights_needed
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_bedroom_off

- alias: Guest Bedroom lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
    # - condition: state
    #   entity_id: group.sleep_status
    #   state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_bedroom_normal

# - alias: Guest Bedroom lights off when guest goes to bed
#   trigger:
#     - platform: state
#       entity_id: group.guest_sleep_status
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: input_boolean.lights_needed
#       state: 'on'
#   action:
#     # - delay: '00:01:00'
#     - service: scene.turn_on
#       entity_id: scene.guest_bedroom_off
