- alias: Disable guest bedroom motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 2002
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 3002
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled

- alias: Enable guest bedroom motion on button click off
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 5002
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled

- alias: Enable guest bedroom motion when no motion for long time
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion_sensor
      to: 'off'
      for: '00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
