- alias: Disable guest bedroom motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 2002
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 3002
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 4002
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled

- alias: Enable guest bedroom motion
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion_sensor
      to: 'off'
      for: '00:10:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 1002
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.light_mode', 'on') %}
          scene.guest_bedroom_idle
          {% else %}
          scene.guest_bedroom_off
          {% endif %}
